framework:
    validation:
        email_validation_mode: html5

        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        #auto_mapping:


#Application\DTO\GetExchangeRateRequest:
#    properties:
#        date:
#            - All:
#                  - NotBlank: ~
#                  - DMYDate: ~
#        targetCurrencyCode:
#            - All:
#                - NotBlank: ~
#                - Currency: ~
#        sourceCurrencyCode:
#            - Currency: ~


when@test:
    framework:
        validation:
            not_compromised_password: false
